# Generated by Django 4.1.1 on 2022-10-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queex_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
